export const API = {
  INSTRUCTOR_STATS: '/instructor/dashboard-stats/',
  INSTRUCTOR_COURSES_MINI: '/instructor/courses-mini/',
  INSTRUCTOR_REVENUE_TREND: '/instructor/revenue-trend/',
  INSTRUCTOR_COURSE_DETAIL: '/instructor/course-detail/',
  COURSE_CREATE: '/instructor/create-course/',
  COURSE_VARIANT_CREATE: '/instructor/course/variant/create/',
  COURSE_VARIANT_DELETE: '/instructor/course/variant/delete/',
  COURSE_VARIANT_ITEM_CREATE: '/instructor/course/variant-item/create/',
  COURSE_VARIANT_ITEM_DELETE: '/instructor/course/variant-item/delete/',
  HOME_FEATURED: '/home/featured-courses/',
  HOME_REVIEWS: '/home/recent-reviews/',
  COURSE_DETAIL: '/course-detail/',
  SEARCH_COURSES: '/course/search/',
  CATEGORY_LIST: '/course/category/',
  STUDENT_COURSES: '/student/courses/',
  STUDENT_COURSE_DETAIL: '/student/course-detail/',
  STUDENT_COURSE_COMPLETED_LESSON: '/student/course/completed-lesson/',
  STUDENT_DASHBOARD_STATS: '/student/dashboard-stats/',
};
